-- 코드를 입력하세요
WITH RECURSIVE ANIMAL_HOUR AS (
  SELECT 0 HOUR
  UNION ALL
  SELECT HOUR + 1
  FROM ANIMAL_HOUR
  WHERE HOUR < 23
)

SELECT h.HOUR HOUR, COUNT(o.DATETIME) COUNT
FROM ANIMAL_HOUR h
LEFT JOIN ANIMAL_OUTS o ON h.HOUR = HOUR(o.DATETIME)
GROUP BY HOUR
ORDER BY HOUR;