-- 2021년에 가입한 전체 회원
SELECT COUNT(*) INTO @U_NUM FROM USER_INFO WHERE YEAR(JOINED) = 2021;

SELECT
YEAR(O.SALES_DATE) AS YEAR,
MONTH(O.SALES_DATE) AS MONTH,
COUNT(DISTINCT O.USER_ID) AS PUCHASED_USERS, -- 상품을 구매한 회원수
ROUND(
    COUNT(DISTINCT O.USER_ID)/@U_NUM, 1 ) AS PUCHASED_RATIO -- 상품을 구매한 회원의 비율
FROM ONLINE_SALE O
JOIN USER_INFO U
ON U.USER_ID = O.USER_ID
WHERE YEAR(U.JOINED) = 2021
GROUP BY 1, 2 -- 년, 월 별로 
ORDER BY 1, 2; -- 전체 결과는 년을 기준으로 오름차순, 월을 기준으로 오름차순 정렬




