-- 코드를 입력하세요
SELECT c.CAR_ID, c.CAR_TYPE, ROUND(c.DAILY_FEE*(100-p.DISCOUNT_RATE)/100*30) FEE
FROM CAR_RENTAL_COMPANY_CAR c, CAR_RENTAL_COMPANY_DISCOUNT_PLAN p 
WHERE c.CAR_TYPE = p.CAR_TYPE
    and c.CAR_TYPE in ('세단', 'SUV')
    and not c.CAR_ID in (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' and END_DATE >= '2022-11-01'
    )
    and p.DURATION_TYPE = '30일 이상'
    and c.DAILY_FEE*(100-p.DISCOUNT_RATE)/100*30 >= 500000
    and c.DAILY_FEE*(100-p.DISCOUNT_RATE)/100*30 < 2000000
GROUP BY c.CAR_ID
ORDER BY FEE DESC, c.CAR_TYPE, c.CAR_ID DESC;