SELECT
B.CATEGORY AS CATEGORY,
SUM(BS.SALES) AS TOTAL_SALES -- 도서 판매량
FROM BOOK B
JOIN BOOK_SALES BS
ON B.BOOK_ID = BS.BOOK_ID
WHERE 
    MONTH(BS.SALES_DATE) = 1 and 
    YEAR(BS.SALES_DATE) = 2022 -- 2022년 1월
GROUP BY B.CATEGORY  --  카테고리 별
ORDER BY B.CATEGORY ASC; -- 카테고리명을 기준으로 오름차순