-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME,SUM(p.PRICE*o.AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT p
JOIN FOOD_ORDER o ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE o.PRODUCE_DATE >= "2022-05-01" and o.PRODUCE_DATE <= "2022-05-31"
GROUP BY p.PRODUCT_ID
ORDER BY TOTAL_SALES desc, PRODUCT_ID