-- 년, 월, 성별 별로 상품을 구매한 회원수
-- 결과는 년, 월, 성별을 기준으로 오름차순 정렬
-- 성별 정보가 없는 경우 결과에서 제외

SELECT
YEAR(SALES_DATE) AS YEAR, 
MONTH(SALES_DATE) AS MONTH, 
U.GENDER AS GENDER, 
COUNT(DISTINCT O.USER_ID) AS USERS # 이부분은 생각 못했...
FROM ONLINE_SALE O
JOIN USER_INFO U ON O.USER_ID = U.USER_ID AND U.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), U.GENDER
ORDER BY 1 ASC, 2 ASC, 3 ASC;