-- 코드를 입력하세요
SELECT YEAR(o.SALES_DATE) YEAR, MONTH(o.SALES_DATE) MONTH, u.GENDER, COUNT(DISTINCT u.USER_ID) USER_ID
FROM USER_INFO u
JOIN ONLINE_SALE o ON u.USER_ID = o.USER_ID AND u.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER