-- 년, 월, 성별 별로 상품을 구매한 회원수를 집계 (오름차순)
-- 특정 월에 중복되는 유저의 거래내역이 있을 수 있으므로 이를 DISTINCT 처리함
SELECT YEAR, MONTH, GENDER, COUNT(DISTINCT(T1.USER_ID)) AS "USERS"
FROM USER_INFO T1,
(
    SELECT ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT,EXTRACT(YEAR FROM SALES_DATE) YEAR,EXTRACT(MONTH FROM SALES_DATE) MONTH
    FROM ONLINE_SALE
) T2
WHERE T1.USER_ID = T2.USER_ID
AND T1.GENDER IS NOT NULL
GROUP BY T2.YEAR, T2.MONTH, T1.GENDER
ORDER BY T2.YEAR, T2.MONTH, T1.GENDER;