-- UNION 으로 하니까 틀리고 UNION ALL로 하니까 성공함.
-- UNION : 합집합 (중복컬럼 제거 O) => 속도 느림
-- UNION ALL : 합집합 (중복컬럼 제거 X)
SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS "SALES_DATE", PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    UNION ALL
    SELECT SALES_DATE, PRODUCT_ID, NULL AS "USER_ID", SALES_AMOUNT
    FROM OFFLINE_SALE
)
WHERE EXTRACT(YEAR FROM SALES_DATE) = '2022'
AND EXTRACT(MONTH FROM SALES_DATE) = '03'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;