-- 코드를 입력하세요
SELECT h.HISTORY_ID,
    ROUND(c.DAILY_FEE*(100-IFNULL(p.DISCOUNT_RATE, 0)) / 100*(DATEDIFF(h.END_DATE, h.START_DATE)+1)) FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
JOIN CAR_RENTAL_COMPANY_CAR c ON h.CAR_ID = c.CAR_ID AND c.CAR_TYPE = '트럭'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p ON c.CAR_TYPE = p.CAR_TYPE AND p.DURATION_TYPE = 
    CASE
        WHEN DATEDIFF(h.END_DATE, h.START_DATE) >= 7 AND DATEDIFF(h.END_DATE, h.START_DATE) < 30 THEN '7일 이상'
        WHEN DATEDIFF(h.END_DATE, h.START_DATE) >= 30 AND DATEDIFF(h.END_DATE, h.START_DATE) < 90 THEN '30일 이상'
        WHEN DATEDIFF(h.END_DATE, h.START_DATE) >= 90 THEN '90일 이상'
    END
ORDER BY FEE DESC, h.HISTORY_ID DESC;