# 즐겨찾기가 가장 많은 식당 정보 출력하기
# 풀이 1
SELECT A.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO A, 
(
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MX_FAV
    FROM REST_INFO 
    GROUP BY 1
) B
WHERE 
    A.FOOD_TYPE = B.FOOD_TYPE 
    AND A.FAVORITES = MX_FAV
ORDER BY 1 DESC;

## 조인을 이용한 풀이
# SELECT A.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
# FROM REST_INFO A
# JOIN (
#     SELECT 
#     FOOD_TYPE, 
#     MAX(FAVORITES) AS MAX_FAV 
#     FROM REST_INFO
#     GROUP BY 1
# ) B
# ON A.FOOD_TYPE = B.FOOD_TYPE AND A.FAVORITES = MAX_FAV
# ORDER BY 1 DESC;
