SELECT
C.CAR_ID, 
C.CAR_TYPE, 
ROUND(C.DAILY_FEE*30*(1-P.DISCOUNT_RATE/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE 
AND C.CAR_TYPE IN ('세단', 'SUV') -- 테이블에서 자동차 종류가 '세단' 또는 'SUV' 인 자동차
AND P.DURATION_TYPE = '30일 이상'
AND NOT C.CAR_ID IN (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= 20221101 -- 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고
)
GROUP BY 1
HAVING FEE >= 500000 AND FEE < 2000000 --  대여 금액이 50만원 이상 200만원 미만인 자동차
ORDER BY 3 DESC, 2 ASC, 1 DESC; -- 대여금액 네림치순, 자동차 종류 오름차순, 자동차 ID 내림차순, 