-- 코드를 입력하세요
SELECT YEAR(o.SALES_DATE) YEAR, MONTH(o.SALES_DATE) MONTH, COUNT(distinct o.USER_ID) PUCHASED_USERS, ROUND(COUNT(distinct o.USER_ID)/(SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) PUCHASED_RATIO
FROM USER_INFO u
JOIN ONLINE_SALE o ON u.USER_ID = o.USER_ID
WHERE YEAR(u.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;
